version: '3.8'

services:
  web:
    build: .
    ports:
      - "8035:8000"
    env_file:
      - .env

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${USERNAME_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=${DATABASE_DB}
    volumes:
      - polls_pg_data:/mcp/postgres

volumes:
  polls_pg_data:
