version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app/startbooks
      - DEBUG=0
    depends_on:
      - db  

  db:
    image: postgres:13
    container_name: startbooks_bd
    environment:
      POSTGRES_DB: startbooks  
      POSTGRES_USER: brunadev  
      POSTGRES_PASSWORD: bruna8596 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432" 

volumes:
  postgres_data:
